export const fa = {
  productName: "هوشمندی پذیرنده",
  productTagline: "تصمیم‌های بهتر، بر پایه داده",
  overview: "نمای کلی",
  insights: "بینش‌ها",
  filters: "فیلترها",
  applyFilters: "اعمال فیلترها",
  resetFilters: "پاک‌کردن فیلترها",
  decisionBrief: "خلاصه تصمیم پذیرنده",
  currentStatus: "وضعیت فعلی",
  mainProblem: "مسئله اصلی",
  opportunity: "فرصت",
  recommendedAction: "اقدام پیشنهادی",
  paymentVolume: "حجم پرداخت",
  successfulSessions: "نشست‌های موفق",
  failedSessions: "نشست‌های ناموفق",
  moreMetrics: "شاخص‌های بیشتر",
  retryRecovery: "بازیابی پس از تلاش مجدد",
  failedSessionRate: "نرخ نشست ناموفق",
  relativeAdjustedFee: "شاخص نسبی کارمزد تعدیل‌شده",
  trend: "روند عملکرد",
  priorityInsight: "بینش اولویت‌دار",
  highestOpportunity: "بیشترین فرصت",
  evidence: "شواهد",
  whyItMatters: "چرا مهم است؟",
  confidence: "سطح اطمینان",
  coverage: "پوشش داده",
  limitation: "محدودیت تحلیل",
  inspectEvidence: "بررسی شواهد",
  calculation: "این عدد چگونه محاسبه شده؟",
  calculationTrace: "ردیابی محاسبه",
  metricDefinition: "تعریف شاخص",
  formula: "فرمول",
  numeratorDenominator: "صورت و مخرج",
  analysisUnit: "واحد تحلیل",
  sourceMetrics: "ستون‌ها و سنجه‌های مبنا",
  activeFilters: "فیلترهای فعال",
  inputRows: "ردیف‌های ورودی",
  usedRows: "ردیف‌های استفاده‌شده",
  missingRows: "مقادیر خالی و ردیف‌های حذف‌شده",
  datasetVersion: "نسخه دیتاست",
  inspectRows: "مشاهده ردیف‌های مبنا",
  merchant: "پذیرنده",
  category: "دسته‌بندی",
  dateRange: "بازه زمانی",
  paymentStatus: "وضعیت پرداخت",
  attemptCount: "تعداد تلاش",
  issuer: "صادرکننده (Issuer)",
  terminal: "پایانه",
  all: "همه",
  from: "از تاریخ",
  to: "تا تاریخ",
  light: "روشن",
  dark: "تاریک",
  system: "سیستم",
  theme: "پوسته",
  datasetConnected: "دیتاست متصل است",
  datasetLoading: "در حال اتصال به دیتاست",
  datasetDisconnected: "اتصال دیتاست برقرار نیست",
  retry: "تلاش دوباره",
  close: "بستن",
  noInsight: "برای دامنه انتخاب‌شده بینش قابل اتکایی تولید نشده است.",
  noTrend: "برای دامنه انتخاب‌شده روندی در دسترس نیست.",
  adjustedFeeWarning:
    "این مقدار برای مقایسه‌های نسبی محاسبه شده و نشان‌دهنده کارمزد واقعی زرین‌پال نیست.",
  aggregateOnly:
    "API این نما فقط داده‌های تجمیعی را ارائه می‌کند و ردیف‌های خام را به مرورگر ارسال نمی‌کند.",
  confidenceText:
    "این تحلیل توصیفی است؛ نتیجه رابطه مشاهده‌شده را نشان می‌دهد و ادعای علّی ندارد.",
} as const;
